Hauki 574 selected resources view (and Hauki 579)
City-of-Helsinki/hauki-admin-ui pull request #345
Opened 2023-10-09 05:03 UTC by timwessman

## Description
- Created batch update resource page view
- This PR contains basics of the view and remove resource functionality (There will be some more features coming in next PRs)
- Tests for the view

## Related Issue
- Jira ticket of the view [HAUKI-574](https://helsinkisolutionoffice.atlassian.net/browse/HAUKI-574)
- Jira ticket of remove resources from the view [HAUKI-579](https://helsinkisolutionoffice.atlassian.net/browse/HAUKI-579)
- [UI Design](https://www.figma.com/file/o9KFjflfk5WiY4Djsg91Vn/HAUKI-small-developments?type=design&node-id=32-16625&mode=design&t=STXL4fepfm7wIkKx-0) 

## How Has This Been Tested?
- Tested running on local machine.
- Unit tests pass

## Known issues
- I'm not sure which format resource ids should be shown in the table
- Table is now paginated with 10 resource pages
- api.GetResources returns resources in different type than `Resource[]` so I'm not sure in which end of the pipe it should be casted better (that's why I need to cast it to `any`. There should be better sollution)

2023-10-09 09:47 UTC, mikkojamG requested changes
Nice work 👍 Left some comments

2023-10-09 09:47 UTC, mikkojamG commented on src/pages/ResourceBatchUpdatePage.test.tsx
> +      .mockImplementation(() => Promise.resolve(true));
Should probably resolve mock resource instead of boolean?

2023-10-09 09:47 UTC, mikkojamG commented on src/pages/ResourceBatchUpdatePage.test.tsx
> +        testResourceBatchUpdatePagePros.targetResourcesString.split(',')
`targetResourcesString` possibly undefined

2023-10-09 09:47 UTC, mikkojamG commented on src/pages/ResourceBatchUpdatePage.tsx
> +  const targetResourcesStorageKey = 'targetResources';
For better readability, could we move this and `language` above closer to `cols` and `rows` further down? I would nicely group constants together 🙂

2023-10-09 11:47 UTC, timwessman commented on src/components/resource-opening-hours/ResourcePeriodsCopyFieldset.test.tsx
> +  targetResources: [{id:'tprek: 1122', name:'testTargetResource'}],
My linter skipped test files,..now fixed all linter warnings

2023-10-09 12:41 UTC, timwessman commented on src/pages/ResourceBatchUpdatePage.test.tsx
> +      .mockImplementation(() => Promise.resolve(testGetResourceResponse));
In these mocks I used only properties used in the component, but as I now fixed tests to be typescript checked I added all properties

2023-10-09 13:02 UTC, timwessman commented on src/pages/ResourceBatchUpdatePage.tsx
> +  const resourceCount = targetResourceData?.targetResources?.length || 0;
almost possible. `onRemove` -event is needed in cols and `targetResourcesStorageKey` is needed in `onRemove` -event.

2023-10-09 13:04 UTC, timwessman commented on src/pages/ResourceBatchUpdatePage.tsx
> +            // for some reason origins are not part of Resource type, this need to be fixed in API
good idea. Didn't do it now, ..maybe tomorrow

2023-10-09 20:05 UTC, timwessman commented on src/pages/ResourceBatchUpdatePage.tsx
> +            // for some reason origins are not part of Resource type, this need to be fixed in API
I moved it to separate callback function, but kept it in the same scope.

2023-10-10 07:13 UTC, mikkojamG requested changes
Good work, spotted couple ts issues. After these I think this is good to go 👍

2023-10-10 07:13 UTC, mikkojamG commented on src/pages/ResourceBatchUpdatePage.test.tsx
> +      testTargetResourceDataAfterRemove.targetResources[0].name
`name` is possibly undefined, can probably just cast as string here 🤔

2023-10-10 07:13 UTC, mikkojamG commented on src/pages/ResourceBatchUpdatePage.test.tsx
> +      testTargetResourceDataAfterRemove.targetResources[1].name
`name` is possibly undefined, can probably just cast as string here 🤔

2023-10-10 07:18 UTC, mikkojamG commented
> Good work, spotted couple ts issues. After these I think this is good to go 👍

Also Azure pipelines have some lint errors that need to be fixed in `ResourceBatchUpdatePage.scss`

2023-10-10 10:07 UTC, merged